require('settings')
require('plugins')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
require('keybindings')
require('nvim-tree-config')
require('autopairs-config')
vim.cmd('colorscheme nord')
